-- Phase 6 Shadow Mode — comparison table (MySQL-oriented; adapt for Postgres)

CREATE TABLE IF NOT EXISTS geo_engine_comparisons (
  id INT AUTO_INCREMENT PRIMARY KEY,
  attempt_id VARCHAR(64) NOT NULL,
  admin_id INT NULL,
  office_id INT NULL,
  office_name VARCHAR(120) NULL,
  legacy_zone VARCHAR(30) NULL,
  legacy_requires_reason TINYINT(1) NULL,
  legacy_distance_m DOUBLE NULL,
  legacy_decision VARCHAR(30) NULL,
  legacy_policy VARCHAR(30) NULL,
  v2_decision VARCHAR(30) NULL,
  v2_policy VARCHAR(30) NULL,
  v2_confidence DOUBLE NULL,
  v2_distance_m DOUBLE NULL,
  decision_match TINYINT(1) NOT NULL DEFAULT 0,
  reason_match TINYINT(1) NOT NULL DEFAULT 0,
  policy_match TINYINT(1) NOT NULL DEFAULT 0,
  difference_category VARCHAR(80) NULL,
  execution_time_legacy_ms DOUBLE NULL,
  execution_time_v2_ms DOUBLE NULL,
  accuracy_m DOUBLE NULL,
  browser VARCHAR(80) NULL,
  device_type VARCHAR(20) NULL,
  direction VARCHAR(10) NULL,
  comparison_status VARCHAR(30) NOT NULL DEFAULT 'ok',
  error_note VARCHAR(200) NULL,
  created_at DATETIME NOT NULL,
  KEY ix_geo_cmp_attempt (attempt_id),
  KEY ix_geo_cmp_admin (admin_id),
  KEY ix_geo_cmp_office (office_id),
  KEY ix_geo_cmp_created (created_at),
  KEY ix_geo_cmp_diff (difference_category),
  KEY ix_geo_cmp_created_match (created_at, decision_match),
  KEY ix_geo_cmp_created_office (created_at, office_id),
  KEY ix_geo_cmp_diff_cat (difference_category, created_at)
);
